name: Audit

on:
  push:
    tags:
      - '*'
  workflow_call:
  workflow_dispatch:

jobs:
  audit:
    name: Audit Formula
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Tap
        run: brew tap swift-psychrometrics/formula
      - name: Audit
        run: brew audit --strict --online psychrometrics
