name: Audit

on:
  pull_request:
    types:
      - opened
  push:
  workflow_dispatch:

jobs:
  audit:
    name: Audit Formula
    runs-on: ubuntu-latest
    container:
      image: homebrew/brew
    steps:
      - uses: actions/checkout@v3
      - name: Tap
        run: brew tap swift-psychrometrics/formula
      - name: Audit
        run: brew audit --strict --online psychrometrics
